language: php
php:
    - 5.6
    - 5.5
    - 5.4
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

install:
    - composer self-update
    - composer install -o --dev

script: ./vendor/bin/phpunit --configuration ./build/travis.phpunit.xml
