language: php
php:
    - 5.6
    - 5.5
    - 5.4
    - hhvm
    - nightly

matrix:
    allow_failures:
        - php: hhvm
        - php: nightly

install:
    - composer self-update
    - composer install -o --dev

script: ./vendor/bin/phpunit --configuration ./build/travis.phpunit.xml
