language: php
php:
    - 5.6
    - 5.5
    - 5.4
    - 5.3
    - 7.0.0
    - 7.0.1
    - hhvm
    - nightly

matrix:
    allow_failures:
        - php: hhvm
        - php: nightly
        - php: 7.0

install:
    - composer self-update
    - composer install -o --dev

script:
    - ./vendor/bin/phpunit --configuration ./build/travis.phpunit.xml
    - bash build/run_benchmarks.sh
