language: php
php:
    - 5.6
    - 5.5
    - 5.4
    - 5.3
    - 7.0
    - 7.1
    - hhvm
    - nightly

matrix:
    allow_failures:
        - php: hhvm
        - php: nightly

install:
    - composer self-update
    - composer install -o --dev

script:
    - composer test-travis-ci
    - composer benchmark
